name: Deploy to server

on:
  push:
    branches: [ "development"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: kronos-python:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy image over SSH
        run: |
          cat /tmp/image.tar |  ssh -v -o StrictHostKeyChecking=no docker-admin@kronos.nl "docker load"

      - name: Deploy on server
        run: |
          ssh -v -o StrictHostKeyChecking=no docker-admin@kronos.nl <<'ENDSSH'
          cd ${{ vars.APP_PATH }}
          make deploy
          ENDSSH
